---
audio:
  bitrate: 48000
  channel_type: mono
  filter: lavfi
days:
  1: 
    date: 2018-07-03T00:00:00
    sessions:
      1:
        recordings:
      2:
        graphics:
          session: "~/Pictures/OPLSS/2018/title card, session 2.1, logo bottom right.png"
        recordings:
          - hoffmann1-1.mp4
          - hoffmann1-2.mp4
          - hoffmann1-3.mp4
      3:
        recordings:
          - hoffmann2-1.mp4
          - hoffmann2-2.mp4
          - hoffmann2-3.mp4
          - hoffmann2-4.mp4
      4:
        recordings:
          - downen2-1.mp4
          - downen2-2.mp4
          - downen2-3.mp4
          - downen2-4.mp4
  2: 
    date: 2018-07-05T00:00:00
    sessions:
      1:
        recordings:
          - hoffmann3-1.mp4
          - hoffmann3-2.mp4
          - hoffmann3-3.mp4
          - hoffmann3-4.mp4
      2:
        recordings:
          - downen3-1.mp4
          - downen3-2.mp4
          - downen3-3.mp4
      3:
        recordings:
          - hoffmann4-1.mp4
          - hoffmann4-2.mp4
          - hoffmann4-3.mp4
  5:
    date: 2018-07-08
    sessions:
      1:
        graphics:
          session: "~/Pictures/OPLSS/2018/title card, session 5.1, logo bottom right.png"
        recordings:
          - MVI_0579.MP4
          - MVI_0580.MP4
          - MVI_0581.MP4
          - MVI_0582.MP4
graphics:
  copyright:
    image_path: "~/Pictures/OPLSS/2018/title card, copyright, logo middle center.png"
  main:
    image_path: "~/Pictures/OPLSS/2018/title card, main, logo middle center.png"
  sponsors:
    image_path: "~/Pictures/OPLSS/2018/title card, sponsors, logo bottom right.png"
image:
  loop_count: 1
  pix_fmt: yuv420p
  title_card_length: 6
recordings:
  base_url: https://www.cs.uoregon.edu/research/summerschool/summer18/lectures/
  cache_directory: "~/Videos/OPLSS/2018/Session 5.1, 2018-07-08"
    #/tmp/oplss/2018/recordings
video:
  codec: libx264
  preset: ntsc
  resolution:
    height: 1080
    width: 1920
