---
base_uri: "https://www.cs.uoregon.edu/research/summerschool/summer18/lectures"
base_path: /home/self/Remote/nas01/universe/Media/Video/OPLSS/2018
file_pattern: "%<speaker>s%<session>d-%<part>d.mp4"
recordings:
  downen:
    5: 3
    6: 3
    7: 3
  hoffmann:
    3: 4
    4: 3
sessions:
  1.1:
    recordings:
      - "/home/self/Remote/nas01/universe/Media/Video/OPLSS/2018/OPLSS 2018, Session 1.1.1.MP4"
      - "/home/self/Remote/nas01/universe/Media/Video/OPLSS/2018/OPLSS 2018, Session 1.1.1.MP4"
      - "/home/self/Remote/nas01/universe/Media/Video/OPLSS/2018/OPLSS 2018, Session 1.1.1.MP4"
